### ISSUE TITLE
Ploting/Rendering CART flipTrees in Shiny

### ISSUE THREAD

**Issue by kocman** [NumbersInternational/flipTrees#2]
Is there a solution to plot fliptreeS in A Shiny App? 
I am using the following Code but havent find a render solution to display it in Shiny

`CART(Kyphosis ~ Age + Number + Start, data = kyphosis)`

**Comment by mwmclean** [comment]
The output of `print(CART(Kyphosis ~ Age + Number + Start, data = kyphosis))` is an object with classes `"rhtmlSankeyTree"`, `"htmlwidget"`, so it should be displayable in a shiny app like any other `htmlwidget`.

**Comment by kocman** [comment]
that helped me! thank you so much!
